export const BRAND = {
  wordmark: "VESTA",
  footerBrand: "VESTA MODA",
  phrase: "Vista o que representa você.",
  instagramLabel: "Instagram",
  whatsappLabel: "WhatsApp",
  backTop: "Voltar ao topo ↑",
  hero: {
    kicker: "Curadoria contemporânea",
    title: "Vista o que representa você.",
    description:
      "Curadoria de peças especiais para todos os estilos, histórias e formas de se expressar.",
    primaryCta: "Explorar curadoria",
    secondaryCta: "Conhecer a Vesta",
    signature: "Moda com personalidade. Escolhas com significado.",
    image:
      "https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1280",
    imageAlt:
      "Mulher estilosa usando camisa oversized e óculos escuros em retrato de moda contemporânea.",
    cardLabel: "Peças com presença",
    cardText: "Seu estilo não precisa pedir licença.",
    badge: "Vesta / 01",
  },
  manifesto: {
    kicker: "Manifesto",
    title: "A Vesta é para você",
    description:
      "Não existe uma idade, um gênero ou um estilo certo para pertencer à Vesta. Existe a vontade de vestir algo que acompanhe quem você é — hoje, por inteiro.",
    pillars: [
      {
        n: "01",
        title: "Personalidade",
        text: "Peças que acompanham sua história, sem tentar encaixar você em uma só definição.",
        tone: "ivory" as const,
      },
      {
        n: "02",
        title: "Curadoria",
        text: "Seleção atenta a acabamento, presença, versatilidade e tudo o que faz uma peça especial.",
        tone: "burgundy" as const,
      },
      {
        n: "03",
        title: "Bem-estar",
        text: "Vestir-se também é se sentir à vontade, confiante e reconhecido em seu próprio ritmo.",
        tone: "ivory" as const,
      },
    ],
  },
  catalog: {
    kicker: "Seleção da semana",
    title: "Curadoria em destaque",
    note: "Peças e valores apresentados apenas para demonstração.",
    searchLabel: "Buscar na curadoria",
    searchPlaceholder: "Buscar peça ou estilo",
    categoryLabel: "Filtrar por categoria",
    styleLabel: "Filtrar por estilo",
    sortLabel: "Ordenar peças",
    priceLabel: "Faixa de preço:",
    emptyTitle: "Ainda não encontramos essa peça",
    emptyText: "Tente outro termo ou remova alguns filtros para reencontrar sua próxima escolha.",
    clearFilters: "Limpar filtros",
  },
  categories: {
    kicker: "Para explorar",
    title: "Categorias que acompanham você",
    text: "Clique em uma categoria e veja as peças correspondentes na curadoria.",
    chips: [
      { label: "Sapatos", href: "/categoria/sapatos" },
      { label: "Bolsas", href: "/categoria/acessorios" },
      { label: "Camisas", href: "/categoria/camisas" },
      { label: "Vestidos", href: "/categoria/vestidos" },
      { label: "Vintage", href: "/categoria/garimpos" },
      { label: "Social", href: "/produtos" },
      { label: "Festa", href: "/produtos?q=festa" },
    ],
    soon: "Novas categorias em breve",
  },
  editorial: {
    kicker: "Vestir como gesto",
    title: "Escolha sentir.",
    text: "A roupa pode ser abrigo, memória, festa e presença. Escolha aquilo que faz você se reconhecer — sem regras prontas, com espaço para a sua própria narrativa.",
  },
  testimonials: {
    kicker: "Impressões",
    title: "Histórias em construção",
    items: [
      {
        quote:
          "Encontrei uma peça que parecia já fazer parte de mim. Essa é uma narrativa demonstrativa de como a experiência Vesta pode ser sentida.",
        author: "Cliente Vesta",
      },
      {
        quote:
          "A curadoria me ajudou a olhar para o meu estilo com mais liberdade. Exemplo ilustrativo, não uma avaliação verificada.",
        author: "Comunidade Vesta",
      },
      {
        quote:
          "Gostei de sentir que a moda aqui conversa com pessoas, e não com rótulos. Texto de exemplo para esta demonstração.",
        author: "Pessoa Vesta",
      },
    ],
  },
  journal: {
    kicker: "Inspiração",
    title: "Diário Vesta",
    articles: [
      {
        category: "Curadoria",
        title: "Menos peças, mais histórias",
        text: "Um olhar sobre escolhas que resistem ao tempo e criam espaço para combinações mais pessoais.",
        image:
          "https://images.pexels.com/photos/5709661/pexels-photo-5709661.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Roupas femininas variadas em cabides de madeira em uma loja.",
      },
      {
        category: "Tendências",
        title: "O tempo das peças com presença",
        text: "Texturas, cortes e detalhes que transformam uma tendência passageira em escolha afetiva.",
        image:
          "https://images.pexels.com/photos/3755706/pexels-photo-3755706.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Casacos e gravatas elegantes em manequins de loja contemporânea.",
      },
      {
        category: "Comportamento",
        title: "Vestir a própria linguagem",
        text: "Uma reflexão sobre moda como linguagem cotidiana, com liberdade para mudar de ideia e de forma.",
        image:
          "https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=800",
        alt: "Pessoa olhando roupas em cabides dentro de boutique estilosa.",
      },
    ],
  },
  contact: {
    kicker: "Vamos conversar",
    title: "A sua história também inspira a Vesta.",
    text: "Conte o que você procura, compartilhe uma ideia ou deixe seu recado. Vamos receber sua mensagem com atenção.",
    name: "Nome",
    email: "E-mail",
    whatsapp: "WhatsApp",
    whatsappOptional: "(opcional)",
    message: "Mensagem",
    submit: "Enviar mensagem",
    disclaimer: "Ao enviar, sua mensagem é salva de forma privada para retorno da Vesta.",
  },
  bag: {
    kicker: "Sua seleção",
    title: "Sacola Vesta",
    empty: "Sua sacola está esperando uma escolha especial.",
    subtotal: "Subtotal",
    checkout: "Finalizar compra",
  },
  footer: {
    navTitle: "Navegue",
    serviceTitle: "Atendimento",
    serviceText: "A Vesta recebe cada mensagem com atenção e cuidado.",
    copy: "© 2026 VESTA MODA",
  },
} as const;

export const FEATURED_PIECES = [
  {
    slug: "blazer-siena",
    name: "Blazer Siena",
    meta: "Blazer · Social · Seminovo",
    category: "Blazers",
    style: "Social",
    priceCents: 48900,
    brand: "Siena",
    size: "M",
    color: "Camelo",
    condition: "VERY_GOOD" as const,
    categorySlug: "blazers-e-casacos",
    description: "Blazer marrom elegante, ombro marcado e caimento de boutique.",
    image: "/curadoria/pexels-photo-19584322.jpg",
    alt: "Blazer marrom elegante em manequim de boutique.",
  },
  {
    slug: "vestido-aurora",
    name: "Vestido Aurora",
    meta: "Vestido · Festa · Especial",
    category: "Vestidos",
    style: "Festa",
    priceCents: 64000,
    brand: "Aurora",
    size: "P",
    color: "Verde",
    condition: "EXCELLENT" as const,
    categorySlug: "vestidos",
    description: "Vestido verde de festa, manga bufante e presença dramática.",
    image: "/curadoria/pexels-photo-35907407.jpg",
    alt: "Pessoa usando vestido verde elegante em iluminação dramática.",
  },
  {
    slug: "camisa-iris",
    name: "Camisa Íris",
    meta: "Camisa · Essencial · Nova",
    category: "Camisas",
    style: "Essencial",
    priceCents: 28900,
    brand: "Íris",
    size: "M",
    color: "Off-white",
    condition: "NEW_WITH_TAG" as const,
    categorySlug: "camisas",
    description: "Camisa de linho minimalista, botões à mostra e caimento leve.",
    image: "/curadoria/pexels-photo-22441297.jpg",
    alt: "Camisa de linho minimalista em cabide de madeira.",
  },
  {
    slug: "bolsa-alba",
    name: "Bolsa Alba",
    meta: "Bolsa · Casual · Especial",
    category: "Bolsas",
    style: "Casual",
    priceCents: 53000,
    brand: "Alba",
    size: "Único",
    color: "Caramelo",
    condition: "EXCELLENT" as const,
    categorySlug: "acessorios",
    description: "Bolsa de couro texturizado, alça curta e presença casual.",
    image: "/curadoria/pexels-photo-28773220.png",
    alt: "Bolsa de couro marrom com textura sofisticada apoiada sobre pedra.",
  },
  {
    slug: "sapato-roma",
    name: "Sapato Roma",
    meta: "Sapato · Social · Vintage",
    category: "Sapatos",
    style: "Social",
    priceCents: 37000,
    brand: "Roma",
    size: "40",
    color: "Caramelo",
    condition: "VINTAGE" as const,
    categorySlug: "sapatos",
    description: "Sapato social de couro vintage, palmilha original e sola honesta.",
    image: "/curadoria/pexels-photo-298863.jpg",
    alt: "Sapatos de couro marrom em loja de roupas.",
  },
  {
    slug: "trench-soleil",
    name: "Trench Soleil",
    meta: "Vintage · Casual · Especial",
    category: "Vintage",
    style: "Vintage",
    priceCents: 71000,
    brand: "Soleil",
    size: "M",
    color: "Khaki",
    condition: "EXCELLENT" as const,
    categorySlug: "garimpos",
    description: "Trench coat urbano, óculos escuros e corte com memória de rua.",
    image: "/curadoria/pexels-photo-22805433.jpg",
    alt: "Mulher com trench coat e óculos escuros em estilo urbano.",
  },
] as const;
